### ISSUE TITLE
想问问博主用的什么框架做的博客？

### ISSUE THREAD

**Issue by NOeSIS-yu** [RiverTwilight/rene.wang#36]
博客样式很新颖，ipad还怪好看的，能给个链接学习一下嘛？

**Comment by RiverTwilight** [comment]
你好，抱歉没有及时回复你，我没有收到通知。

我使用 [NextJS](https://nextjs.org/) 来搭建了这个博客。你可以跟着官网教程很轻松的入手。

为了实现样式效果，我还单独开发了一个 React 组件库 [kindle-ui](https://github.com/RiverTwilight/kindle-ui)。
